# [keyboard]
# bindings = [{ action = "SpawnNewInstance", key = "N", mods = "Control" }]

[scrolling]
history = 100000
multiplier = 3

[window]
dynamic_title = true 
opacity = 1
padding.x = 5
padding.y = 5
dimensions.columns = 160
dimensions.lines   = 45

[font]
normal.family = "Iosevka Fixed"
normal.style  = "Regular"
size = 14

[colors]
primary.foreground = "#eeeeee"
primary.background = "#121212"
draw_bold_text_with_bright_colors = false

